// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using WebKit;

namespace WebViewInteraction.iOS
{
	public partial class CallNativeFunctionViewController : UIViewController, IWKScriptMessageHandler
	{
		public CallNativeFunctionViewController (IntPtr handle) : base (handle)
		{

		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			var userController = new WKUserContentController();
			userController.AddScriptMessageHandler(this, "NOTE_HERE");
			var config = new WKWebViewConfiguration
			{
				UserContentController = userController
			};

			this.webView = new WKWebView(this.View.Frame, config)
			{
				WeakNavigationDelegate = this
			};

			this.View.AddSubview(webView);

			webView.LoadHtmlString(@"
			<html>
				<head>
					<title>Local String</title>
					<meta name='viewport' content='width = device-width, initial-scale = 1' />
					<style type='text/css'>p{font-family : Verdana; color : purple }</style>
					<script language='JavaScript'>
						function sendData(){window.webkit.messageHandlers.NOTE_HERE.postMessage('from HTML');};
					</script>
				</head>
				<body>
					<p>Hello World!</p><br />
					<button type='button' onclick='sendData()' text='sendData'>sendData</button>
				</body>
			</html>", null);

		}



		public override void DidReceiveMemoryWarning ()
		{		
			base.DidReceiveMemoryWarning ();		
			// Release any cached data, images, etc that aren't in use.		
		}

        public void DidReceiveScriptMessage(WKUserContentController userContentController, WKScriptMessage message)
        {
			Console.WriteLine(message.Body.ToString());
		}
    }

    
}
